version: "3.8"

services:
  nextjs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://django-backend:8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
