services:
  django-backend:
    build:
      context: ./backend/radhesgar_blogs
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/radhesgar_blogs/db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
      - ./media:/media
    env_file:
      - .env
    environment:
      - DEBUG=0
    networks:
      - app-network
    restart: unless-stopped

  nextjs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://django-backend:8000
    depends_on:
      - django-backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - django-backend
      - nextjs-frontend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  static_volume:

networks:
  app-network:
    driver: bridge
