version: "3.8"

services:
  django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - DEBUG=0
    networks:
      - app-network
    restart: unless-stopped

volumes:
  sqlite_data:
  static_volume:

networks:
  app-network:
    driver: bridge
